version: '3.6'
services:
  ccxt-rest-NIS:
    image: registry.nordlicht.cloud/ccxt-rest-nis:0.1.0
    hostname: ccxt-rest-nis
    ports:
      - 3000:3000
    networks:
      localdocker:
        aliases:
          - ccxt-rest-nis

networks:
  localdocker:
    driver: bridge